CREATE DATABASE Managers_db;
use Managers_db;

CREATE TABLE Managers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    manager VARCHAR(255) NOT NULL,
    building VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);